import { Tile } from '../../../app/shared/models/tile.model';

export const TilesStub: Tile[] = [
	{
		id: 1,
		color: 'red',
		victoryPoints: 6,
		imagePath: '',
		type: 'small-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 2,
		color: 'red',
		victoryPoints: 6,
		imagePath: '',
		type: 'small-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 3,
		color: 'red',
		victoryPoints: 6,
		imagePath: '',
		type: 'small-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 4,
		color: 'red',
		victoryPoints: 6,
		imagePath: '',
		type: 'small-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 5,
		color: 'red',
		victoryPoints: 6,
		imagePath: '',
		type: 'small-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 6,
		color: 'red',
		victoryPoints: 6,
		imagePath: '',
		type: 'small-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 7,
		color: 'red',
		victoryPoints: 6,
		imagePath: '',
		type: 'small-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 8,
		color: 'red',
		victoryPoints: 6,
		imagePath: '',
		type: 'small-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 9,
		color: 'red',
		victoryPoints: 4,
		imagePath: '',
		type: 'large-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 10,
		color: 'red',
		victoryPoints: 4,
		imagePath: '',
		type: 'large-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 11,
		color: 'red',
		victoryPoints: 4,
		imagePath: '',
		type: 'large-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 12,
		color: 'red',
		victoryPoints: 4,
		imagePath: '',
		type: 'large-market',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 13,
		color: 'red',
		victoryPoints: 8,
		imagePath: '',
		type: 'oasis',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 14,
		color: 'red',
		victoryPoints: 8,
		imagePath: '',
		type: 'oasis',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 15,
		color: 'red',
		victoryPoints: 8,
		imagePath: '',
		type: 'oasis',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 16,
		color: 'red',
		victoryPoints: 8,
		imagePath: '',
		type: 'oasis',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 17,
		color: 'red',
		victoryPoints: 8,
		imagePath: '',
		type: 'oasis',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 18,
		color: 'red',
		victoryPoints: 8,
		imagePath: '',
		type: 'oasis',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 19,
		color: 'blue',
		victoryPoints: 5,
		imagePath: '',
		type: 'village',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 20,
		color: 'blue',
		victoryPoints: 5,
		imagePath: '',
		type: 'village',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 21,
		color: 'blue',
		victoryPoints: 5,
		imagePath: '',
		type: 'village',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 22,
		color: 'blue',
		victoryPoints: 5,
		imagePath: '',
		type: 'village',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 22,
		color: 'blue',
		victoryPoints: 5,
		imagePath: '',
		type: 'village',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 24,
		color: 'blue',
		victoryPoints: 6,
		imagePath: '',
		type: 'sacred-place',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 25,
		color: 'blue',
		victoryPoints: 6,
		imagePath: '',
		type: 'sacred-place',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 26,
		color: 'blue',
		victoryPoints: 6,
		imagePath: '',
		type: 'sacred-place',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 27,
		color: 'blue',
		victoryPoints: 6,
		imagePath: '',
		type: 'sacred-place',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 28,
		color: 'blue',
		victoryPoints: 10,
		imagePath: '',
		type: 'sacred-place',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 29,
		color: 'blue',
		victoryPoints: 12,
		imagePath: '',
		type: 'sacred-place',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	},
	{
		id: 30,
		color: 'blue',
		victoryPoints: 15,
		imagePath: '',
		type: 'sacred-place',
		position: null,
		meeples: [],
		palacesCount: 0,
		palmaTreesCount: 0,
		action: '',
	}
]
